/groups/behroozi/hbowden/cocoa/Cocoa/installation_scripts/create_link_all_projects.sh: line 55: /dev/tty: No such device or address
Traceback (most recent call last):
  File "/groups/behroozi/hbowden/cocoa/Cocoa/projects/roman_real/test_dv.py", line 168, in <module>
    train_samples, train_data_vectors = local_data_vector_list(params_train, rank, label_train)
NameError: name 'local_data_vector_list' is not defined
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[27642,1],0]
  Exit code:    1
--------------------------------------------------------------------------
